apiVersion: apps/v1
kind: Deployment
metadata:
  name: cepheus-deployment
  namespace: fiware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cepheus
  template:
    metadata:
      labels:
        app: cepheus
    spec:
      containers:
      - name: cepheus
        image: orangeopensource/fiware-cepheus:1.0.0
        ports:
        - containerPort: 8080
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: cepheus
  namespace: fiware
spec:
  selector:
    app: cepheus
  type: NodePort
  ports:
  - name: cep-port
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30004
  - name: broker-port
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30005
